// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Work Package → Tasks*
 */
export interface WorkPackageDocumentDataTasksItem {
  /**
   * Task field in *Work Package → Tasks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Put task of WP
   * - **API ID Path**: work_package.tasks[].task
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  task: prismic.KeyTextField;
}

type WorkPackageDocumentDataSlicesSlice = ResultsSlice;

/**
 * Content for Work Package documents
 */
interface WorkPackageDocumentData {
  /**
   * title field in *Work Package*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Put title WP
   * - **API ID Path**: work_package.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Tasks field in *Work Package*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: work_package.tasks[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tasks: prismic.GroupField<Simplify<WorkPackageDocumentDataTasksItem>>;

  /**
   * Slice Zone field in *Work Package*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: work_package.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<WorkPackageDocumentDataSlicesSlice>;
}

/**
 * Work Package document from Prismic
 *
 * - **API ID**: `work_package`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorkPackageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<WorkPackageDocumentData>,
    'work_package',
    Lang
  >;

export type AllDocumentTypes = WorkPackageDocument;

/**
 * Item in *Results → Default → Primary → Result*
 */
export interface ResultsSliceDefaultPrimaryResultPartnerItem {
  /**
   * Task name field in *Results → Default → Primary → Result*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: results.default.primary.result_partner[].task_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  task_name: prismic.KeyTextField;

  /**
   * Task Result field in *Results → Default → Primary → Result*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: results.default.primary.result_partner[].task_result
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  task_result: prismic.KeyTextField;
}

/**
 * Primary content in *Results → Default → Primary*
 */
export interface ResultsSliceDefaultPrimary {
  /**
   * Name Partner field in *Results → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Put name of partner
   * - **API ID Path**: results.default.primary.name_partner
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name_partner: prismic.KeyTextField;

  /**
   * Result field in *Results → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: results.default.primary.result_partner[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  result_partner: prismic.GroupField<
    Simplify<ResultsSliceDefaultPrimaryResultPartnerItem>
  >;
}

/**
 * Default variation for Results Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ResultsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ResultsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Results*
 */
type ResultsSliceVariation = ResultsSliceDefault;

/**
 * Results Shared Slice
 *
 * - **API ID**: `results`
 * - **Description**: Results
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ResultsSlice = prismic.SharedSlice<
  'results',
  ResultsSliceVariation
>;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      WorkPackageDocument,
      WorkPackageDocumentData,
      WorkPackageDocumentDataTasksItem,
      WorkPackageDocumentDataSlicesSlice,
      AllDocumentTypes,
      ResultsSlice,
      ResultsSliceDefaultPrimaryResultPartnerItem,
      ResultsSliceDefaultPrimary,
      ResultsSliceVariation,
      ResultsSliceDefault,
    };
  }
}
